# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loopC <- function(nodelist, al, x, x2, pm, Lix, finind) {
    .Call('indelmiss_loopC', PACKAGE = 'indelmiss', nodelist, al, x, x2, pm, Lix, finind)
}

allpatt_loopC <- function(nodelist, al, x, x2, pm_plc, Lix, finind) {
    .Call('indelmiss_allpatt_loopC', PACKAGE = 'indelmiss', nodelist, al, x, x2, pm_plc, Lix, finind)
}

